name: credit_card_slider
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-216.0.dev <3.0.0'

dependencies:
  cupertino_icons:
  intl:
  flutter_spinkit:
  auto_size_text:
  simple_animations:
  get:
  get_it:
  get_storage:
  gson:
  logger:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/
    - assets/images/
#  fonts:
#    - family: WorkSans
#      fonts:
#        - asset: assets/fonts/WorkSans-Regular.ttf
#        - asset: assets/fonts/WorkSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/WorkSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/WorkSans-Bold.ttf
#          weight: 700
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Bold.ttf
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Medium.ttf
#          weight: 400